serviceAccount:
  name: cluster-autoscaler
  annotations: {}
  # Since we're using EKS Pod Identity (not IRSA), the Helm chart needs to be told not to create its own service account annotations (IRSA-style), and the service account name must match exactly what you set in aws_eks_pod_identity_association(cluster-autoscaler).

autoDiscovery:
  clusterName: staging-demo-eks

awsRegion: us-east-1

rbac:
  create: true

extraArgs:
  balance-similar-node-groups: "true"
  skip-nodes-with-local-storage: "false"
  expander: "least-waste"

resources:
  limits:
    cpu: 200m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 300Mi

replicaCount: 1

podDisruptionBudget:
  maxUnavailable: 1

image:
  tag: v1.36.0