clusterName: staging-demo-eks

replicaCount: 2

serviceAccount:
  name: aws-load-balancer-controller
  annotations: {}

ingressClassConfig:
  default: false

logLevel: info

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podDisruptionBudget:
  maxUnavailable: 1
 