"clusterName": "staging-demo-eks"
"fullnameOverride": "aws-load-balancer-controller"
"ingressClassConfig":
  "default": false
"logLevel": "info"
"podDisruptionBudget":
  "maxUnavailable": 1
"replicaCount": 2
"resources":
  "limits":
    "cpu": "500m"
    "memory": "512Mi"
  "requests":
    "cpu": "100m"
    "memory": "128Mi"
"serviceAccount":
  "annotations": {}
  "name": "aws-load-balancer-controller"
"vpcId": "vpc-0681a3cd12b4d149e"
