apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd # App object data so argocd knows it deployed the app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io # so when the metrics server is deleted all child processes get deleted as well
spec:
  project: default
  sources:
    # source 1 for helm chart
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: 1.21.0 
      helm:
        valueFiles:
          - $values/argoCD/environments/dev/cert_manager_values.yaml
        # Hard-coded parameter override to force ArgoCD's generator engine
        parameters:
          - name: crds.enabled
            value: "true"

    # Source 2 for the values file
    - repoURL: 'https://github.com/BhupeshDahiya/learning_eks' # Change to your Git URL
      targetRevision: HEAD # Or pin to a specific branch like 'main' or a tag or a commit
      ref: values  
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager # usually needs its own namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status