apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd # App object data so argocd knows it deployed the app
  finalizers:
    - resources-finalizer.argocd.argoproj.io # so when the metrics server is deleted all child processes get deleted as well
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # aws_alb.yaml gets wave "0"
spec:
  project: default
  sources:
    # source 1 for helm chart
    - repoURL: 'https://kubernetes.github.io/ingress-nginx'
      chart: ingress-nginx
      targetRevision: 4.15.1
      helm:
        valueFiles:
          - $values/argoCD/environments/dev/nginx_ingress_values.yaml

    # Source 2 for the values file
    - repoURL: 'https://github.com/BhupeshDahiya/learning_eks' # Change to your Git URL
      targetRevision: HEAD # Or pin to a specific branch like 'main' or a tag or a commit
      ref: values  
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system # metrics server is usually deployed here

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true